function _renderDigits(container, text, options){ if(!container) return; container.innerHTML = ''; const opt = Object.assign({path:'assets/external/SpaceShooterRedux/PNG/UI', w:12, h:18}, options||{}); const s = String(text); for(const ch of s){ if(/[0-9]/.test(ch)){ const img = document.createElement('img'); img.src = `${opt.path}/numeral${ch}.png`; img.width = opt.w; img.height = opt.h; img.style.imageRendering = 'pixelated'; container.appendChild(img); } else { const span = document.createElement('span'); span.textContent = ch; span.style.marginLeft = '2px'; span.style.marginRight = '2px'; span.style.color = '#ffd27f'; container.appendChild(span); } } }

export function setPercent(val){ const el = document.getElementById('percent'); if(!el) return; const v = Math.round(Number(val) || 0); el.innerHTML = ''; const digits = document.createElement('div'); digits.style.display = 'flex'; digits.style.alignItems = 'center'; _renderDigits(digits, String(v).padStart(3,' '), {w:18,h:22}); const pct = document.createElement('div'); pct.textContent = '%'; pct.style.marginLeft = '6px'; pct.style.color = '#7efcff'; pct.style.fontWeight='700'; pct.style.textShadow='0 0 6px rgba(0,240,255,0.2)'; el.appendChild(digits); el.appendChild(pct); }

export function setScore(val){ const el = document.getElementById('score'); if(!el) return; const s = Math.max(0, Math.floor(Number(val) || 0)); const digitsContainer = el.querySelector('.digits') || el; _renderDigits(digitsContainer, String(s).padStart(6,'0'), {w:12,h:18}); }

export function setLives(val){ const el = document.getElementById('lives'); if(!el) return; el.innerHTML = ''; const count = Math.max(0, Number(val) || 0); for(let i=0;i<count;i++){ const img = document.createElement('img'); img.src = 'assets/external/SpaceShooterRedux/PNG/UI/playerLife1_blue.png'; img.alt = 'life'; el.appendChild(img); } if(count > 5){ const span = document.createElement('span'); span.style.marginLeft = '6px'; span.textContent = `x${count}`; el.appendChild(span); } }

export function setLevel(val){ const el = document.getElementById('level'); if(!el) return; const n = Number(val) || 0; el.textContent = `LVL: ${String(n).padStart(2,'0')}`; }
export function setMultiplier(val){ const el = document.getElementById('mult'); if(!el) return; el.textContent = `MULT: x${val}`; }
export function setStatus(text){ const el = document.getElementById('status'); if(el) el.textContent = `Status: ${text}`; }
export function setHighScore(val, flash=false){ const el = document.getElementById('highscore'); if(!el) return; const s = Math.max(0, Math.floor(Number(val) || 0)); const digitsContainer = el.querySelector('.digits') || el; _renderDigits(digitsContainer, String(s).padStart(6,'0'), {w:12,h:18}); if(flash){ el.style.color = '#ff0'; setTimeout(()=>{ el.style.color = ''; }, 1200); } }
export function setSuperText(text){ const el = document.getElementById('super'); if(el) el.textContent = text || ''; }
export function setEnemies(current, total){ const el = document.getElementById('enemies'); if(!el) return; el.textContent = `ENEMIES: ${current}/${total}`; }
export function setPowerup(type, ttl){ const el = document.getElementById('powerup'); if(!el) return; el.textContent = type ? `POWERUP: ${type}${ttl?(' ('+ttl.toFixed(1)+'s)'):''}` : ''; }
export function setAmmo(ammo){ const el = document.getElementById('ammo'); if(!el) return; el.textContent = `AMMO: ${ammo}`; }
export function setBossHP(hp, max){ const el = document.getElementById('bosshp'); if(!el) return; if(hp === null) el.textContent = ''; else el.textContent = `BOSS HP: ${hp}/${max}`; }
export function setLevelName(name){ const el = document.getElementById('levelname'); if(!el) return; el.textContent = name ? `${String(name).toUpperCase()}` : ''; }

// Display detected cave/area overlays. `caves` is an array of cave objects
// returned from Board.detectCaves. Each cave should include `id` and `color`.
export function setCaves(caves){ const cnt = (caves && caves.length) ? caves.length : 0; const el = document.getElementById('areas-count'); if(el) el.textContent = `Areas: ${cnt}`; const list = document.getElementById('areas-list'); if(!list) return; list.innerHTML = ''; if(!caves || !caves.length) return; for(const c of caves){ const wrapper = document.createElement('div'); wrapper.style.display = 'flex'; wrapper.style.alignItems = 'center'; wrapper.style.gap = '6px'; const sw = document.createElement('div'); sw.style.width = '20px'; sw.style.height = '14px'; sw.style.background = c.color || 'rgba(48,200,255,0.12)'; sw.style.border = `1px solid ${c.strokeColor || 'rgba(48,200,255,0.6)'}`; sw.style.borderRadius = '2px'; const label = document.createElement('div'); label.style.fontSize = '12px'; label.style.color = '#ddd'; label.textContent = `#${c.id} (${c.cells.length})`; wrapper.appendChild(sw); wrapper.appendChild(label); list.appendChild(wrapper); } }
